context:
  version: "1.2.6"

package:
  name: dot-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/dot-language-server/-/dot-language-server-${{ version }}.tgz
  sha256: 9dd2e0ba6514b3e06818b95cfb4d1eb3d7387e274cc0a8181bd9cbe058025995

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - dot-language-server --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A language server for the DOT language
  homepage: https://github.com/nikeee/dot-language-server
  repository: https://github.com/nikeee/dot-language-server

extra:
  recipe-maintainers:
    - danielnachun
