context:
  version: "3.0.0"

package:
  name: dot-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/dot-language-server/-/dot-language-server-${{ version }}.tgz
  sha256: 438fe415b240aa2607a8f63166b8b066f73314d40f404ad08e2777f5e1ba1b25

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - dot-language-server --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A language server for the DOT language
  homepage: https://github.com/nikeee/dot-language-server
  repository: https://github.com/nikeee/dot-language-server

extra:
  recipe-maintainers:
    - danielnachun
