context:
  version: "3.0.1"

package:
  name: dot-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/dot-language-server/-/dot-language-server-${{ version }}.tgz
  sha256: 2512e4aba7d8b4cfb8d606b18782f9a668c287b989fb0b49250090cc0275cf2a

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - dot-language-server --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A language server for the DOT language
  homepage: https://github.com/nikeee/dot-language-server
  repository: https://github.com/nikeee/dot-language-server

extra:
  recipe-maintainers:
    - danielnachun
